const ATTACK_NAMES: Record<string, string> = {
  Absorb: "Absorver",
  Amass: "Acumular",
  "Ancient Whirlpool": "Redemoinho",
  "Aqua Edge": "Gume d'Água",
  Attach: "Anexar",
  "Barrier Attack": "Barreira",
  Bite: "Mordida",
  Blizzard: "Nevasca",
  Blot: "Borrão",
  "Bone Beatdown": "Paulada Óssea",
  Bonemerang: "Ossomerangue",
  Bother: "Incomodar",
  "Bubble Drain": "Dreno de Bolha",
  "Bug Bite": "Picada",
  "Call for Family": "Chamar a Família",
  "Circle Circuit": "Circuito",
  Combustion: "Combustão",
  "Continuous Lick": "Lambida",
  "Copy Anything": "Copiar Tudo",
  Corner: "Encurralar",
  "Crimson Storm": "Tormenta Rubra",
  Crunch: "Triturar",
  Dig: "Cavar",
  "Dizzy Punch": "Soco Tonto",
  "Do the Wave": "Fazer a Onda",
  "Double Horn": "Chifre Duplo",
  "Double Lariat": "Lariat Duplo",
  "Double-Edge": "Gume Duplo",
  "Draco Meteor": "Meteoro Draco",
  "Drill Peck": "Bicada Broca",
  "Drill Run": "Corrida Broca",
  Drool: "Babar",
  "Electro Ball": "Bola Elétrica",
  Ember: "Brasa",
  "Fight Back": "Revidar",
  "Find a Friend": "Achar Amigo",
  "Fire Blast": "Rajada de Fogo",
  "Fire Claws": "Garras de Fogo",
  "Fire Mane": "Juba de Fogo",
  "Fire Spin": "Giro de Fogo",
  Flamethrower: "Lança-Chamas",
  Flap: "Bater Asa",
  Flare: "Labareda",
  Flop: "Tombo",
  "Gentle Slap": "Tapinha",
  "Giant Bloom": "Flor Gigante",
  Glide: "Planar",
  Gnaw: "Roer",
  Growl: "Rosnado",
  Gust: "Lufada",
  "Head Bolt": "Raio na Cabeça",
  Headache: "Dor de Cabeça",
  Headbutt: "Cabeçada",
  "Heart Stamp": "Selo Cardíaco",
  "Heat Blast": "Rajada de Calor",
  "Heat Tackle": "Investida Quente",
  "Heavy Impact": "Impacto Pesado",
  "Horn Attack": "Chifrada",
  "Horn Drill": "Broca de Chifre",
  "Horn Hazard": "Chifre Arriscado",
  "Hydro Bazooka": "Hidro Bazuca",
  "Hydro Pump": "Jato d'Água",
  "Hydro Splash": "Hidro Splash",
  "Hyper Beam": "Hiper-raio",
  "Hyper Voice": "Hipervoz",
  "Ice Beam": "Raio de Gelo",
  "Ice Wing": "Asa de Gelo",
  "Inferno Dance": "Dança Infernal",
  "Inferno Onrush": "Ímpeto Infernal",
  Jab: "Jabe",
  "KO Crab": "Nocaute",
  "Knock Back": "Empurrão",
  "Knuckle Punch": "Soco de Punho",
  "Land Crush": "Esmagar",
  "Leaf Supply": "Suprimento de Folha",
  "Leech Life": "Sanguessuga",
  "Leek Slap": "Tapa de Alho-poró",
  "Lightning Ball": "Bola de Raio",
  Lovestrike: "Golpe do Amor",
  "Low Kick": "Rasteira",
  "Magical Shot": "Tiro Mágico",
  "Magma Punch": "Soco de Magma",
  "Mega Drain": "Megadreno",
  "Mega Punch": "Megassoci",
  "Metal Claw": "Garra de Metal",
  "Mist Slash": "Corte de Névoa",
  "Mud-Slap": "Tapa de Lama",
  Mumble: "Resmungo",
  "Pay Day": "Dia do Pago",
  Peck: "Bicada",
  Pierce: "Perfurar",
  "Pin Missile": "Míssil Agulha",
  "Poison Gas": "Gás Venenoso",
  "Poison Horn": "Chifre Venenoso",
  "Poison Powder": "Pó Venenoso",
  "Poison Tentacles": "Tentáculos Tóxicos",
  Pound: "Pancada",
  "Powder Snow": "Neve em Pó",
  "Power Blast": "Rajada Potente",
  "Primal Wingbeat": "Batida Primordial",
  Psychic: "Psíquico",
  "Psychic Sphere": "Esfera Psíquica",
  Psydrive: "Psicodrive",
  Psypunch: "Socopsíquico",
  Psyshot: "Tiro Psíquico",
  "Quick Attack": "Ataque Rápido",
  "Raging Thunder": "Trovão Furioso",
  "Rain Splash": "Salpico",
  Ram: "Investida",
  "Razor Fin": "Nadadeira Afiada",
  "Razor Leaf": "Folha Navalha",
  "Rolling Tackle": "Investida Rolante",
  Rollout: "Rolamento",
  Scratch: "Arranhão",
  "Second Strike": "Segundo Golpe",
  "Seed Bomb": "Bomba de Semente",
  "Seismic Toss": "Arremesso Sísmico",
  "Shadow Claw": "Garra Sombria",
  "Sharp Scythe": "Foice Afiada",
  "Sharp Sting": "Ferrão Afiado",
  Sharpen: "Afiar",
  "Shell Attack": "Ataque de Concha",
  "Sky Attack": "Ataque do Céu",
  Slap: "Tapa",
  Slash: "Talho",
  "Sleepy Song": "Canção Sonolenta",
  Smack: "Bofetada",
  "Soothing Scent": "Aroma Calmante",
  "Spinning Attack": "Ataque Giratório",
  "Spiral Kick": "Chute Espiral",
  Splash: "Borrifo",
  "Spooky Shot": "Tiro Assustador",
  Sting: "Ferrão",
  Stomp: "Pisoteio",
  Strength: "Força",
  "Stretch Kick": "Chute Alongado",
  "Suffocating Gas": "Gás Sufocante",
  "Super Psy Bolt": "Super-raio Psi",
  Surf: "Surfar",
  "Surprise Attack": "Ataque Surpresa",
  Tackle: "Investida",
  "Tail Smack": "Tapa de Cauda",
  "Tail Whap": "Paulada de Cauda",
  "Tail Whip": "Chicote de Cauda",
  Teleport: "Teleporte",
  "Thunder Fang": "Presa Trovejante",
  "Thunder Punch": "Soco Trovejante",
  "Thunder Shock": "Choque do Trovão",
  "Thunder Spear": "Lança do Trovão",
  Thunderbolt: "Trovão",
  "Thundering Hurricane": "Furacão Trovejante",
  "Tiny Charge": "Carga Miúda",
  "Tongue Slap": "Tapa de Língua",
  "Tropical Swing": "Balanço Tropical",
  Venoshock: "Venenochoque",
  "Vine Whip": "Chicote de Vinha",
  "Vise Grip": "Agarrão",
  "Water Arrow": "Flecha d'Água",
  "Water Drip": "Gota d'Água",
  "Water Gun": "Pistola d'Água",
  "Wave Splash": "Onda",
  "Will-O-Wisp": "Fogo-fátuo",
  "Wing Attack": "Ataque de Asa",
  "Zap Kick": "Chute Zap",
};

function translateAttackName(attackName: string) {
  const translated = ATTACK_NAMES[attackName];
  if (!translated) throw new Error(`Ataque sem tradução: ${attackName}`);
  return translated;
}

export { ATTACK_NAMES, translateAttackName };
