ALTER TABLE "cards" ADD COLUMN "number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (sequence name "cards_number_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
WITH numbered AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS n
  FROM "cards"
)
UPDATE "cards" AS c
SET "number" = numbered.n
FROM numbered
WHERE c.id = numbered.id;--> statement-breakpoint
SELECT setval(
  'cards_number_seq',
  GREATEST(COALESCE((SELECT MAX("number") FROM "cards"), 1), 1),
  (SELECT COUNT(*) > 0 FROM "cards")
);--> statement-breakpoint
CREATE UNIQUE INDEX "cards_number_idx" ON "cards" USING btree ("number");
